spring:
  datasource-write:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:~/write;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  datasource-read:
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:~/read;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialects: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: false
    hibernate:
      ddl-auto: none